version: 0.2

phases:
  pre_build:
    commands:
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - REPO=$(aws ecr describe-repositories --repository-name iida-hakone --output text --query "repositories[0].repositoryUri")
    - IMAGE=$REPO0:latest
  biuld:
    commands:
    - docker build -t $IMAGE
    - docker push $IMAGE
  post_build:
    commands:
    - printf '[{"name":"iida-hakone", "imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json