version: 0.2

phases:
  pre_build:
    commands:
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - REPO=$(aws ecr describe-repositories --repository-name iida_hakone --output text --query "repositories[0].repositoryUri")
    - IMAGE=$REPO0:latest
  build:
    commands:
    - docker build -t 667009429896.dkr.ecr.ap-northeast-1.amazonaws.com/iida_hakone:latest .
    - docker push 667009429896.dkr.ecr.ap-northeast-1.amazonaws.com/iida_hakone:latest
  post_build:
    commands:
    - printf '[{"name":"iida_hakone", "imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
